Repository redislabs-training/ru204, pull requests merged in 2022-10, with the labels that each got.

#37 Moved to Jedis 4.3.0 release (was snapshot).
  src/java/jedis_example/pom.xml
Labels: enhancement

#38 Section 2 minor fixes
  courseware/html/section_2/ru204_2_2_1_using_redisjson_in_a_python_application.html
  courseware/html/section_2/ru204_2_3_1_what_are_ulids.html
  courseware/html/section_2/ru204_2_3_2_document_modeling_with_redis_om_for_python.html
Labels: hacktoberfest-accepted

#40 Minor changes section 4.5.0
  courseware/html/section_4/ru204_4_5_0_hands_on_exercise.html
Labels: hacktoberfest-accepted

#39 Section 3 minor fixes
  courseware/html/section_3/ru204_3_2_1_hands_on_exercise.html
  courseware/html/section_3/ru204_3_3_1_hands_on_exercise.html
Labels: hacktoberfest-accepted

#42 Fixed a couple of encodings.
  courseware/html/section_3/ru204_3_2_1_hands_on_exercise.html
Labels: bug
